ALU Control Unit for the RV64I
skudlur/diablo pull request #22
Opened 2023-05-05 18:02 UTC by akarxxx1030

Portrays the functionality of an ALU Control Unit in the RISCV spec.

2023-05-05 18:27 UTC, JoyenBenitto requested changes

2023-05-05 18:27 UTC, JoyenBenitto commented on rtl/alu_control.sv
> +//////////////////////////////////////////////////////////////////////////////////
Remove everything from line 1 -20

2023-05-05 18:27 UTC, JoyenBenitto commented on rtl/alu_control.sv
> +module alu_control #(parameter N=4)(a,b,c,d); //variables instantiated for functional operation
Use relevant variable names

2023-05-06 04:37 UTC, skudlur requested changes
@akarxxx1030 please format the code according to coderule.md. Make sure you give indentation

2023-05-06 05:14 UTC, JoyenBenitto approved these changes

2023-05-06 13:43 UTC, skudlur approved these changes

2023-05-06 13:43 UTC, merged